### PR TITLE
Added codenarc

### PR DESCRIPTION
**Pull request by rkuris**
'gradle check' is how you run it, producing an HTML report

### CODE REVIEW

**Comment by rtyler** [comment]
Where will this put an HTML report? If it goes into `docs/html5` we can publish it on the site too

**Comment by rkuris** [comment]
build/reports/codenarc/cucumber.html is the default location; I think it can be changed but I'd have to look into it.

**Comment by rtyler** [comment]
@rkuris nah that's fine, that's where test reports and things like that go already

**Comment by rtyler** [comment]
This work has been incorporated into #69

**Pull request closed without merging**
