### PR TITLE
Added docs for DeployDB launch and models configuration

### PR DESCRIPTION
**Pull request by maheshkelkar**

### CODE REVIEW

**Comment by maheshkelkar** [comment]
@GiriDandu please review as well. I couldn't add you to assignee or notify list

**Comment by GiriDandu** [comment]
>Models-Configuration Management: 
Can we have following sections. It's kind of easier to understand.
Goals: State the requirements. Operator is allowed to change the config anytime in the deployment flow etc
Design: How it is done - checksum etc
Limitations: Only allow to be backward compatible one version etc

**Comment by maheshkelkar** [comment]
> Goals: State the requirements. Operator is allowed to change the config 
> anytime in the deployment flow etc
> Design: How it is done - checksum etc

ok, we can do that. But, is there a problem with current writeup. Is it falling short of communicating the intent.

> Limitations: Only allow to be backward compatible one version etc

Sorry, I am not sure I understand this comment. Can you please elaborate?

**Comment by rtyler** [comment]
:+1:  from my side

**Pull request merged**
